# Generated by Django 5.2.13 on 2026-05-03 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment_category', models.CharField(choices=[('shirt', 'Shirt'), ('pant', 'Pant'), ('indowestern', 'Indowestern'), ('2pc_indowestern', '2-Piece Indowestern'), ('shervani', 'Shervani'), ('jodhpuri', 'Jodhpuri'), ('open_jodhpuri', 'Open Jodhpuri'), ('jabbha', 'Jabbha'), ('2pc_shervani', '2-Piece Shervani'), ('2pc_jodhpuri', '2-Piece Jodhpuri'), ('lengho', 'Lengho')], max_length=30)),
                ('values', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='customers.customer')),
            ],
        ),
    ]
