# Generated by Django 5.1.7 on 2026-05-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_measurement_unique_customer_garment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGarmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='measurement',
            name='garment_category',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='CustomGarmentParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('category_name', 'name')},
            },
        ),
    ]
