# Generated by Django 5.1.7 on 2026-05-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_customgarmentcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='is_sample_product',
            field=models.BooleanField(default=False),
        ),
    ]
