# Generated by Django 5.2.13 on 2026-07-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_measurement_is_sample_product'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='measurement',
            name='unique_measurement_per_customer_garment',
        ),
    ]
