# Generated by Django 5.1.7 on 2026-05-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_backfill_order_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='garment_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
