# Generated by Django 5.1.7 on 2026-05-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_garment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI / QR Code'), ('card', 'Credit / Debit Card'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=20),
        ),
    ]
