# Generated by Django 5.1.7 on 2026-05-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_red_flagged',
            field=models.BooleanField(default=False, help_text='Mark if the garment/catalog is unavailable in-store and must be ordered from a 3rd party.', verbose_name='Red Flag (Outsource Required)'),
        ),
    ]
