# Generated by Django 5.1.7 on 2026-05-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_is_red_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='is_buy_back',
            field=models.BooleanField(default=False, help_text='Check if this order is a buy back.', verbose_name='Buy Back'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deposit_paid',
            field=models.BooleanField(default=False),
        ),
    ]
