# Generated by Django 5.2.13 on 2026-05-09 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_deposit_amount_order_is_buy_back_and_more'),
        ('salesperson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='salesperson.salesperson'),
        ),
    ]
