# Generated by Django 5.1.7 on 2026-06-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_salesperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Mark if this outsourced order requires urgent processing.', verbose_name='Urgent'),
        ),
    ]
